name: weather_forecast
description: An app that shows weather forecast
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.2.0+1
environment:
  sdk: ">=3.3.2 <4.0.0"
dependencies:
  about: ^2.1.3
  cached_network_image: ^3.3.1
  community_charts_flutter: ^1.0.2
  cupertino_icons: ^1.0.6
  dynamic_color: ^1.7.0
  flex_seed_scheme: ^1.5.0
  flutter:
    sdk: flutter
  flutter_settings_screens: ^0.3.3-null-safety+2
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  http: ^1.2.1
  intl: ^0.18.1
  url_launcher: ^6.2.5
  weather_icons: ^3.0.0
dev_dependencies:
  build_runner: ^2.4.9
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  windows:
    generate: true
  web:
    generate: true
  macos:
    generate: true
  image_path: "assets/icon/app.png"
flutter_native_splash:
  # flutter pub run flutter_native_splash:create
  # flutter pub run flutter_native_splash:remove
  color: "#0277BD"
  image: assets/icon/app.png
  # TODO: add support of dark splash
  # The color_dark, background_image_dark, and image_dark are parameters that set the background
  # and image when the device is in dark mode. If they are not specified, the app will use the
  # parameters from above. If the image_dark parameter is specified, color_dark or
  # background_image_dark must be specified.  color_dark and background_image_dark cannot both be
  # set.
  #color_dark: "#042a49"
  #background_image_dark: "assets/dark-background.png"
  #image_dark: assets/splash-invert.png
flutter:
  uses-material-design: true
  assets:
    - README.md
    - LICENSE.md
    - assets/icon/app.png
    - assets/background/welcome/bottom-left.png
    - assets/background/welcome/top-left.png
    - assets/background/welcome/right.png
